#spring.application.name=auth-server-sso
server:
  port: 8081

logging:
  level:
    root: INFO
    com.demosso.authorizationserver: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demosso
    username: postgres
    password: 19pool90
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      connection-test-query: "SELECT 1"
      connectionTimeout: 30000
      validation-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      auto: none

  flyway:
    url: jdbc:postgresql://localhost:5432/demosso
    user: postgres
    password: 19pool90
